#!/usr/bin/env python
# --------------------------------------------------------------------------- #
# HELP - Rotate tab-separated rows with columns

import csv
import sys
from builtins import range

rows = list(csv.reader(sys.stdin, dialect="excel-tab"))
writer = csv.writer(sys.stdout, dialect="excel-tab")
for col in range(0, len(rows[0])):
    writer.writerow([row[col] for row in rows])
